# Generated by Django 6.0.5 on 2026-06-11 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dadjokes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='contributor',
            field=models.TextField(default='Admin'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='picture',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
