# Generated by Django 6.0.5 on 2026-06-11 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dadjokes', '0002_picture_contributor_picture_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture',
            name='contributor',
        ),
    ]
