# Generated by Django 6.0.5 on 2026-06-11 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dadjokes', '0003_remove_picture_contributor'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='contributor',
            field=models.TextField(default='Karachi'),
            preserve_default=False,
        ),
    ]
