# Generated by Django 6.0.5 on 2026-06-09 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini_insta', '0008_alter_follow_follower_profile_alter_follow_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follow',
            name='follower_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower_profile', to='mini_insta.profile'),
        ),
        migrations.AlterField(
            model_name='follow',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='mini_insta.profile'),
        ),
    ]
