# Generated by Django 6.0.5 on 2026-06-23 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crochet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='commenter',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='favoriter',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='creator',
            field=models.TextField(),
        ),
    ]
